{% set version = "1.6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-opdisdownsampling
  version: "{ version|replace("-", "_") }}"

source:
  url:
    - {{ cran_mirror }}/src/contrib/opdisDownsampling_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/opdisDownsampling/opdisDownsampling_{{ version }}.tar.gz
  sha256: ccf6e2c480f5c77549e77b6d410d8ec93902a7496c0c21eb0630364851b27949

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib('c') }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib('m2w64_c') }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=1.0.0
    - r-catools
    - r-doparallel
    - r-foreach
    - r-pbmcapply
    - r-pracma
    - r-twosamples
  run:
    - r-base
    - r-rcpp >=1.0.0
    - r-catools
    - r-doparallel
    - r-foreach
    - r-pbmcapply
    - r-pracma
    - r-twosamples

test:
  commands:
    - $R -e "library('opdisDownsampling')"           # [not win]
    - "\"%R%\" -e \"library('opdisDownsampling')\""  # [win]

about:
  home: https://github.com/JornLotsch/opdisDownsampling
  license: GPL-3.0-only
  summary: An optimized method for distribution-preserving class-proportional down-sampling of
    bio-medical data <doi:10.1371/journal.pone.0255838>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
