{% set version = "1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-opdisdownsampling
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/opdisDownsampling_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/opdisDownsampling/opdisDownsampling_{{ version }}.tar.gz
  sha256: 54824939fd62f06f53ca642793f36dd1f3bcc9e45ea825596bdaab01d17295ad

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-benchmarkme
    - r-catools
    - r-doparallel
    - r-foreach
    - r-memuse
    - r-pracma
    - r-twosamples
  run:
    - r-base
    - r-benchmarkme
    - r-catools
    - r-doparallel
    - r-foreach
    - r-memuse
    - r-pracma
    - r-twosamples

test:
  commands:
    - $R -e "library('opdisDownsampling')"           # [not win]
    - "\"%R%\" -e \"library('opdisDownsampling')\""  # [win]

about:
  home: https://cran.r-project.org/package=opdisDownsampling
  license: GPL-3.0-only
  summary: An optimized method for distribution-preserving class-proportional down-sampling of bio-medical data.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
